# Binding solc to <0.8.20 because of bug in 0.8.21
# https://github.com/foundry-rs/foundry/issues/5762
# https://github.com/ethereum/solidity/issues/14430

# Further binding to 0.8.19 because Base has not 
# executed Shanghai upgrade and safer to keep binded

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.19"
optimizer_runs = 1000000
evm_version = "paris"
via_ir = true

[fmt]
number_underscore = "thousands"
single_line_statement_blocks = "multi"
